name: msdip
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.13
  - torchvision
  - matplotlib
  - numpy
  - scipy
  - scikit-image
  - jupyter
  - pip
  - pip:
      - imageio
